name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
            fetch-depth: 0

    - name: What
      run: if [ ${GITHUB_REF##*/} = "main" ]; then echo "BRANCH=latest" >> $GITHUB_ENV; else echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV; fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        tags: |
          ghcr.io/syntheticgestalt/ssh-server:${{ env.BRANCH }}
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64
        secrets: |
          "root_password=${{ secrets.ROOT_PASSWORD }}"
